name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
      node-version: '18'
      cache: 'npm'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cordova CLI
      run: npm install -g cordova@latest

    - name: Install dependencies
      run: |
        cd mjmarkgen-app
        npm install
        ls -la

    - name: Build Android APK (Release)
      run: npm run build
      working-directory: mjmarkgen-app

    - name: Build Android APK (Debug)
      run: cordova build android --debug
      working-directory: mjmarkgen-app

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          mjmarkgen-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          mjmarkgen-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release of MJ MarkGen Android APK

          ## Download
          - **app-debug.apk**: Debug version for testing
          - **app-release-unsigned.apk**: Release version (unsigned)

          ## Installation
          1. Enable "Unknown Sources" in Android Settings
          2. Download and install the APK file
          3. Launch the MJ MarkGen app

          Built from commit: ${{ github.sha }}
        files: |
          mjmarkgen-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          mjmarkgen-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
